# Generated by Django 5.1.3 on 2024-11-30 11:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="favorite",
            old_name="liked",
            new_name="is_liked",
        ),
    ]
