# Generated by Django 5.1.3 on 2025-01-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_rename_liked_favorite_is_liked"),
    ]

    operations = [
        migrations.AddField(
            model_name="userotp",
            name="is_validated",
            field=models.BooleanField(default=False),
        ),
    ]
