# Generated by Django 5.1.3 on 2024-11-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userotp_otp_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='userotp',
            name='block_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
