# Generated by Django 5.1.3 on 2024-11-17 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userotp_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userotp',
            name='block_time',
        ),
        migrations.AlterField(
            model_name='userotp',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='otp', to=settings.AUTH_USER_MODEL),
        ),
    ]
